### ISSUE TITLE
Marked as malware by Chrome Webstore

### ISSUE THREAD

**Issue by lostpg** [huhu/cpp-search-extension#14]
Now is unavailable is Chrome Webstore. What happened?

**Comment by Folyd** [comment]
Chrome removed my extension due to I didn't fix the permission violation in 14 days. (Sorry, I'm busy these days)
However, don't worry, I have republished a new version without the `tabs` permissions, and it will be available again soon.

![origin_img_v2_1ff24c1b-01b3-49d8-83d6-d98b5ee7444g](https://user-images.githubusercontent.com/3369694/177001011-519731fc-006d-4a8e-b314-7ca7c9e0dec1.jpg)

**Comment by Folyd** [comment]
I'll close this issue since the new version already available again.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/3369694/177687960-596b23cb-eb04-45f9-a701-17e879025871.png">
